apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-gitops-app
spec:
  replicas: 1
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
  selector:
    matchLabels:
      app: my-gitops-app
  template:
    metadata:
      labels:
        app: my-gitops-app
    spec:
      containers:
      - name: my-gitops-app
        image: your-registry-url/my-gitops-app:v1
        ports:
        - containerPort: 5000