apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: planet
spec:
  replicas: 1
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
  selector:
    matchLabels:
      app: planet
  template:
    metadata:
      labels:
        app: planet
    spec:
      containers:
      - name: planet
        image: docker.io/rajeshreddy0/planet:v2
        ports:
        - containerPort: 5000